### ISSUE TITLE
Deployments are not  linked in the website

### ISSUE THREAD

**Issue by bsipocz** [scientific-python/tools.scientific-python.org#53]
We need to find a place to linked the deployed dashboards, e.g. devstats, the backport bot, etc. Currently all links are pointing to the github repos instead and I believe we should have both as both of these examples are using multiple repos, apps, etc for a successful deployment rather than being a simple one repo small tool like e.g. the pytest plugins.

**Comment by jarrodmillman** [comment]
You can link to whatever you want on the cards. So it may, in some cases, just be a matter of links to something other than the repo.

For some projects, there will be a website. For others, it is unlikely we will have anything more than a repo. Some projects may want online documentation, but don't want to have their own website. For example, we could make a project page for spin here `https://tools.scientific-python.org/utilities/spin` or `https://tools.scientific-python.org/spin` and have the spin card on `https://tools.scientific-python.org/utilities` link to it.

PR #54 update the devstats card to point to the website and includes the link to the repo in the card body.
